### ISSUE TITLE
make error during libmolgrid step

### ISSUE THREAD

**Issue by claggner** [gnina/gnina#269]
### Issue summary

I'm trying to compile gnina v1.1 on a fresh Ubuntu 22.04 wsl installation, but the _make_ step fails with an error that I can't interpret.

```
[ 84%] Built target test_gridinterp_cpp
[ 86%] Building CXX object test/CMakeFiles/test_mgrid_cpp.dir/test_mgrid.cpp.o
In file included from /usr/local/cuda-12/include/cub/util_device.cuh:52,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12/include/thrust/detail/temporary_array.h:47,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.inl:35,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.h:150,
                 from /usr/local/cuda-12/include/thrust/detail/scan.inl:32,
                 from /usr/local/cuda-12/include/thrust/scan.h:1664,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.inl:40,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.h:95,
                 from /usr/local/cuda-12/include/thrust/detail/reduce.inl:33,
                 from /usr/local/cuda-12/include/thrust/reduce.h:789,
                 from /home/christian/Download/gnina/build/libmolgrid-prefix/src/libmolgrid/test/test_mgrid.cpp:10:
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘void cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC()’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:271:5: error: ‘__syncthreads’ was not declared in this scope
  271 |     __syncthreads();
      |     ^~~~~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC_AND(int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:280:12: error: ‘__syncthreads_and’ was not declared in this scope
  280 |     return __syncthreads_and(p);
      |            ^~~~~~~~~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC_OR(int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:289:12: error: ‘__syncthreads_or’ was not declared in this scope
  289 |     return __syncthreads_or(p);
      |            ^~~~~~~~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘void cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_SYNC(unsigned int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:298:5: error: ‘__syncwarp’ was not declared in this scope
  298 |     __syncwarp(member_mask);
      |     ^~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_ANY(int, unsigned int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:307:12: error: ‘__any_sync’ was not declared in this scope
  307 |     return __any_sync(member_mask, predicate);
      |            ^~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_ALL(int, unsigned int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:316:12: error: ‘__all_sync’ was not declared in this scope
  316 |     return __all_sync(member_mask, predicate);
      |            ^~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_BALLOT(int, unsigned int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:325:12: error: ‘__ballot_sync’ was not declared in this scope
  325 |     return __ballot_sync(member_mask, predicate);
      |            ^~~~~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘unsigned int cub::CUB_200400___CUDA_ARCH_LIST___NS::SHFL_IDX_SYNC(unsigned int, int, unsigned int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:368:12: error: ‘__shfl_sync’ was not declared in this scope
  368 |     return __shfl_sync(member_mask, word, src_lane);
      |            ^~~~~~~~~~~
/usr/local/cuda-12/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::RowMajorTid(int, int, int)’:
/usr/local/cuda-12/include/cub/util_ptx.cuh:415:39: error: ‘threadIdx’ was not declared in this scope
  415 |     return ((block_dim_z == 1) ? 0 : (threadIdx.z * block_dim_x * block_dim_y)) +
      |                                       ^~~~~~~~~
In file included from /usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/barrier_cluster.h:30,
                 from /usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx.h:74,
                 from /usr/local/cuda-12/include/cuda/ptx:19,
                 from /usr/local/cuda-12/include/cuda/discard_memory:25,
                 from /usr/local/cuda-12/include/cub/util_device.cuh:57,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12/include/thrust/detail/temporary_array.h:47,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.inl:35,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.h:150,
                 from /usr/local/cuda-12/include/thrust/detail/scan.inl:32,
                 from /usr/local/cuda-12/include/thrust/scan.h:1664,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.inl:40,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.h:95,
                 from /usr/local/cuda-12/include/thrust/detail/reduce.inl:33,
                 from /usr/local/cuda-12/include/thrust/reduce.h:789,
                 from /home/christian/Download/gnina/build/libmolgrid-prefix/src/libmolgrid/test/test_mgrid.cpp:10:
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘uint32_t cuda::ptx::__4::__as_ptr_smem(const void*)’:
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:40:44: error: ‘__cvta_generic_to_shared’ was not declared in this scope
   40 |   return static_cast<_CUDA_VSTD::uint32_t>(__cvta_generic_to_shared(__ptr));
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘uint64_t cuda::ptx::__4::__as_ptr_gmem(const void*)’:
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:60:44: error: ‘__cvta_generic_to_global’ was not declared in this scope
   60 |   return static_cast<_CUDA_VSTD::uint64_t>(__cvta_generic_to_global(__ptr));
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘_Tp* cuda::ptx::__4::__from_ptr_smem(size_t)’:
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:73:33: error: there are no arguments to ‘__cvta_shared_to_generic’ that depend on a template parameter, so a declaration of ‘__cvta_shared_to_generic’ must be available [-fpermissive]
   73 |   return reinterpret_cast<_Tp*>(__cvta_shared_to_generic(__ptr));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:73:33: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘_Tp* cuda::ptx::__4::__from_ptr_gmem(size_t)’:
/usr/local/cuda-12/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:94:33: error: there are no arguments to ‘__cvta_global_to_generic’ that depend on a template parameter, so a declaration of ‘__cvta_global_to_generic’ must be available [-fpermissive]
   94 |   return reinterpret_cast<_Tp*>(__cvta_global_to_generic(__ptr));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/cuda-12/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12/include/thrust/detail/temporary_array.h:47,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.inl:35,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/scan_by_key.h:150,
                 from /usr/local/cuda-12/include/thrust/detail/scan.inl:32,
                 from /usr/local/cuda-12/include/thrust/scan.h:1664,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.inl:40,
                 from /usr/local/cuda-12/include/thrust/system/detail/generic/reduce_by_key.h:95,
                 from /usr/local/cuda-12/include/thrust/detail/reduce.inl:33,
                 from /usr/local/cuda-12/include/thrust/reduce.h:789,
                 from /home/christian/Download/gnina/build/libmolgrid-prefix/src/libmolgrid/test/test_mgrid.cpp:10:
/usr/local/cuda-12/include/cub/util_device.cuh: In static member function ‘static typename AgentT::TempStorage& cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_helper_impl<AgentT>::get_temp_storage(cub::CUB_200400___CUDA_ARCH_LIST___NS::NullType&, cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_t&)’:
/usr/local/cuda-12/include/cub/util_device.cuh:160:63: error: ‘blockIdx’ was not declared in this scope
  160 |       static_cast<char*>(vsmem.gmem_ptr) + (vsmem_per_block * blockIdx.x));
      |                                                               ^~~~~~~~
/usr/local/cuda-12/include/cub/util_device.cuh: In static member function ‘static bool cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_helper_impl<AgentT>::discard_temp_storage(typename AgentT::TempStorage&)’:
/usr/local/cuda-12/include/cub/util_device.cuh:201:38: error: ‘threadIdx’ was not declared in this scope
  201 |     const std::size_t linear_tid   = threadIdx.x;
      |                                      ^~~~~~~~~
/usr/local/cuda-12/include/cub/util_device.cuh:202:50: error: ‘blockDim’ was not declared in this scope
  202 |     const std::size_t block_stride = line_size * blockDim.x;
      |                                                  ^~~~~~~~
make[5]: *** [test/CMakeFiles/test_mgrid_cpp.dir/build.make:76: test/CMakeFiles/test_mgrid_cpp.dir/test_mgrid.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1164: test/CMakeFiles/test_mgrid_cpp.dir/all] Error 2
make[3]: *** [Makefile:146: all] Error 2
make[2]: *** [CMakeFiles/libmolgrid.dir/build.make:86: libmolgrid-prefix/src/libmolgrid-stamp/libmolgrid-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:414: CMakeFiles/libmolgrid.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### Steps to reproduce
```
git clone https://github.com/gnina/gnina.git
cd gnina
git checkout v1.1
mkdir build
cd build
cmake ..
make
```

### Your system configuration
Operating system: wsl2 install of Ubuntu 22.04.3 LTS
```
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 12.5.82
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0
--   Git               :   v1.1
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -Wno-deprecated-declarations -Wno-unknown-pragmas -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
--
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   0
--   USE_LEVELDB       :   0
--   USE_LMDB          :   0
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
--
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.74)
--   glog              :   Yes
--   gflags            :   Yes
--   OpenBabel         :   No
--   protobuf          :   Yes (ver. ..)
--   CUDA              :   Yes (ver. 12.5)
--
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 9.2.1)
--
-- Python:
--   Interpreter       :   /usr/bin/python3 (ver. 3.10.12)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython3.10.so (ver 3.10.12)
--   NumPy             :   /usr/lib/python3/dist-packages/numpy/core/include (ver 1.21.5)
--
-- Documentaion:
--   Doxygen           :   /usr/bin/doxygen (1.9.1)
--   config_file       :   /home/christian/Download/gnina/caffe/.Doxyfile
--
-- Install:
--   Install path      :   /usr/local

```

**Comment by dkoes** [comment]
Thanks for the bug report.  It looks like CUDA 12.5 changed how thrust includes were processed, breaking things.  I have updated the molgrid code to be compatible with 12.5.  A fresh checkout should work now.

**Comment by claggner** [comment]
Thanks! It does proceed now, but fails a bit later on. Is this the same problem?

```
Consolidate compiler generated dependencies of target caffe
[  0%] Building CXX object caffe/src/caffe/CMakeFiles/caffe.dir/layers/cudnn_softmax_layer.cpp.o
In file included from /usr/local/cuda-12.5/include/cub/util_device.cuh:52,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12.5/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12.5/include/thrust/detail/vector_base.h:39,
                 from /usr/local/cuda-12.5/include/thrust/device_vector.h:34,
                 from /home/christian/Download/gnina/caffe/src/caffe/layers/cudnn_softmax_layer.cpp:4:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘void cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC()’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:271:5: error: ‘__syncthreads’ was not declared in this scope
  271 |     __syncthreads();
      |     ^~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC_AND(int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:280:12: error: ‘__syncthreads_and’ was not declared in this scope
  280 |     return __syncthreads_and(p);
      |            ^~~~~~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::CTA_SYNC_OR(int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:289:12: error: ‘__syncthreads_or’ was not declared in this scope
  289 |     return __syncthreads_or(p);
      |            ^~~~~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘void cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_SYNC(unsigned int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:298:5: error: ‘__syncwarp’ was not declared in this scope
  298 |     __syncwarp(member_mask);
      |     ^~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_ANY(int, unsigned int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:307:12: error: ‘__any_sync’ was not declared in this scope
  307 |     return __any_sync(member_mask, predicate);
      |            ^~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_ALL(int, unsigned int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:316:12: error: ‘__all_sync’ was not declared in this scope
  316 |     return __all_sync(member_mask, predicate);
      |            ^~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::WARP_BALLOT(int, unsigned int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:325:12: error: ‘__ballot_sync’ was not declared in this scope
  325 |     return __ballot_sync(member_mask, predicate);
      |            ^~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘unsigned int cub::CUB_200400___CUDA_ARCH_LIST___NS::SHFL_IDX_SYNC(unsigned int, int, unsigned int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:368:12: error: ‘__shfl_sync’ was not declared in this scope
  368 |     return __shfl_sync(member_mask, word, src_lane);
      |            ^~~~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_ptx.cuh: In function ‘int cub::CUB_200400___CUDA_ARCH_LIST___NS::RowMajorTid(int, int, int)’:
/usr/local/cuda-12.5/include/cub/util_ptx.cuh:415:39: error: ‘threadIdx’ was not declared in this scope
  415 |     return ((block_dim_z == 1) ? 0 : (threadIdx.z * block_dim_x * block_dim_y)) +
      |                                       ^~~~~~~~~
In file included from /usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/barrier_cluster.h:30,
                 from /usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx.h:74,
                 from /usr/local/cuda-12.5/include/cuda/ptx:19,
                 from /usr/local/cuda-12.5/include/cuda/discard_memory:25,
                 from /usr/local/cuda-12.5/include/cub/util_device.cuh:57,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12.5/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12.5/include/thrust/detail/vector_base.h:39,
                 from /usr/local/cuda-12.5/include/thrust/device_vector.h:34,
                 from /home/christian/Download/gnina/caffe/src/caffe/layers/cudnn_softmax_layer.cpp:4:
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘uint32_t cuda::ptx::__4::__as_ptr_smem(const void*)’:
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:40:44: error: ‘__cvta_generic_to_shared’ was not declared in this scope
   40 |   return static_cast<_CUDA_VSTD::uint32_t>(__cvta_generic_to_shared(__ptr));
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘uint64_t cuda::ptx::__4::__as_ptr_gmem(const void*)’:
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:60:44: error: ‘__cvta_generic_to_global’ was not declared in this scope
   60 |   return static_cast<_CUDA_VSTD::uint64_t>(__cvta_generic_to_global(__ptr));
      |                                            ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘_Tp* cuda::ptx::__4::__from_ptr_smem(size_t)’:
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:73:33: error: there are no arguments to ‘__cvta_shared_to_generic’ that depend on a template parameter, so a declaration of ‘__cvta_shared_to_generic’ must be available [-fpermissive]
   73 |   return reinterpret_cast<_Tp*>(__cvta_shared_to_generic(__ptr));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:73:33: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h: In function ‘_Tp* cuda::ptx::__4::__from_ptr_gmem(size_t)’:
/usr/local/cuda-12.5/include/cuda/std/detail/libcxx/include/__cuda/ptx/instructions/../ptx_helper_functions.h:94:33: error: there are no arguments to ‘__cvta_global_to_generic’ that depend on a template parameter, so a declaration of ‘__cvta_global_to_generic’ must be available [-fpermissive]
   94 |   return reinterpret_cast<_Tp*>(__cvta_global_to_generic(__ptr));
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/util.h:48,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/internal/copy_cross_system.h:49,
                 from /usr/local/cuda-12.5/include/thrust/system/cuda/detail/copy.h:111,
                 from /usr/local/cuda-12.5/include/thrust/system/detail/adl/copy.h:50,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/copy.h:98,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/allocator/copy_construct_range.h:53,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.inl:31,
                 from /usr/local/cuda-12.5/include/thrust/detail/contiguous_storage.h:243,
                 from /usr/local/cuda-12.5/include/thrust/detail/vector_base.h:39,
                 from /usr/local/cuda-12.5/include/thrust/device_vector.h:34,
                 from /home/christian/Download/gnina/caffe/src/caffe/layers/cudnn_softmax_layer.cpp:4:
/usr/local/cuda-12.5/include/cub/util_device.cuh: In static member function ‘static typename AgentT::TempStorage& cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_helper_impl<AgentT>::get_temp_storage(cub::CUB_200400___CUDA_ARCH_LIST___NS::NullType&, cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_t&)’:
/usr/local/cuda-12.5/include/cub/util_device.cuh:160:63: error: ‘blockIdx’ was not declared in this scope
  160 |       static_cast<char*>(vsmem.gmem_ptr) + (vsmem_per_block * blockIdx.x));
      |                                                               ^~~~~~~~
/usr/local/cuda-12.5/include/cub/util_device.cuh: In static member function ‘static bool cub::CUB_200400___CUDA_ARCH_LIST___NS::detail::vsmem_helper_impl<AgentT>::discard_temp_storage(typename AgentT::TempStorage&)’:
/usr/local/cuda-12.5/include/cub/util_device.cuh:201:38: error: ‘threadIdx’ was not declared in this scope
  201 |     const std::size_t linear_tid   = threadIdx.x;
      |                                      ^~~~~~~~~
/usr/local/cuda-12.5/include/cub/util_device.cuh:202:50: error: ‘blockDim’ was not declared in this scope
  202 |     const std::size_t block_stride = line_size * blockDim.x;
      |                                                  ^~~~~~~~
make[2]: *** [caffe/src/caffe/CMakeFiles/caffe.dir/build.make:468: caffe/src/caffe/CMakeFiles/caffe.dir/layers/cudnn_softmax_layer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1325: caffe/src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by dkoes** [comment]
Yes, this is in issue within the caffe library, which is no longer part of gnina.  If you remove the line `#include "thrust/device_vector.h"` from `gnina/caffe/src/caffe/layers/cudnn_softmax_layer.cpp` it will compile with CUDA 12.5.

**Comment by claggner** [comment]
Awesome. I ran into one more bump - for some reason `/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.74.0` was missing from the following files 

```
caffe/tools/CMakeFiles/extract_features.dir/link.txt
caffe/tools/CMakeFiles/upgrade_net_proto_binary.dir/link.txt
caffe/tools/CMakeFiles/upgrade_net_proto_text.dir/link.txt
caffe/tools/CMakeFiles/upgrade_solver_proto_text.dir/link.txt
caffe/examples/CMakeFiles/convert_cifar_data.dir/link.txt
```

But adding the link allowed me to finish the installation. 

Thanks so much for your help, David.
