### ISSUE TITLE
Compilation error at cnn_visualization.cpp.o

### ISSUE THREAD

**Issue by test-user-18** [gnina/gnina#19]
`[ 48%] Building CXX object gninasrc/CMakeFiles/gninalib.dir/gninavis/cnn_visualization.cpp.o
/path/gnina/gninasrc/gninavis/cnn_visualization.cpp: In member function ‘std::string cnn_visualization::get_xyz_from_index(int, bool)’:
/path/gnina/gninasrc/gninavis/cnn_visualization.cpp:824:20: error: use of deleted function ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’
         mol_stream = std::stringstream(lig_string);`

If you know anything about this, please let me know.

Thank you.

**Comment by dkoes** [comment]
Perhaps you could provide some additional information, such as what operating system you are using and the version of the compiler?

**Comment by test-user-18** [comment]
Thank you for your reply. Here is the additional information:

- Operating System
SLES 12 SP1
3.12.49-11-default

- gcc
version 4.8.5 (SUSE Linux)

- nvcc
Cuda compilation tools, release 8.0, V8.0.61

**Comment by dkoes** [comment]
It's your version of gcc.  It's too old.  Works fine with 5.4.

**Comment by test-user-18** [comment]
Thank you for letting me know. I will try with gcc 5.4.

**Comment by quantumania** [comment]
Dr. Koes, 

Could you please provide the details of your Linux configuration that was used to successfully compile gnina and Caffe? 

I compiled gcc-5.4 on my current Linux set up (default is gcc-4.8.5) and am still having issues. First, gcc-5.4 is not supported by cuda 8.0, I had manually commented out gcc-5 check in host_config.h. Second, gcc-5.4 is in conflict with system libs compatible with gcc-4.8.5 ...

[ 40%] Linking CXX executable upgrade_solver_proto_text
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()'
../lib/libcaffe.so.1.0.0-rc3: undefined reference to `OpenBabel::OBConversion::ReadFile(OpenBabel::OBBase*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'

**Comment by dkoes** [comment]
We start with a Ubuntu 16.04 image.  Perhaps you do not have the most recent version of CUDA 8?  We don't need to modify anything for the compiler to work.  CUDA 9 works fine as well.  If you don't want to try to fix this to your setup, you could use nvidia-docker and a vanilla ubuntu image to get up and running.
